add drift detection temp ip logic

diff --git a/.github/workflows/tf-drift.yml b/.github/workflows/tf-drift.yml
--- a/.github/workflows/tf-drift.yml
+++ b/.github/workflows/tf-drift.yml
@@ -1,9 +1,9 @@
-name: 'Terraform Configuration Drift Detection'
+name: "Terraform Configuration Drift Detection"
 
 on:
-  workflow_dispatch: 
+  workflow_dispatch:
   schedule:
-    - cron: '41 3 * * *' # runs nightly at 3:41 am
+    - cron: "41 3 * * *" # runs nightly at 3:41 am
 
 #Special permissions required for OIDC authentication
 permissions:
@@ -11,7 +11,7 @@ permissions:
   contents: read
   issues: write
 
-#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
+#These environment variables are used by the terraform azure provider to setup OIDD authenticate.
 env:
   ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
   ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
@@ -20,7 +20,7 @@ env:
 
 jobs:
   terraform-plan:
-    name: 'Terraform Plan'
+    name: "Terraform Plan"
     runs-on: ubuntu-latest
     env:
       #this is needed since we are running terraform with read-only permissions
@@ -29,81 +29,150 @@ jobs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v5
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout
+        uses: actions/checkout@v5
 
-    # Install the latest version of the Terraform CLI
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_wrapper: false
+      # Install the latest version of the Terraform CLI
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_wrapper: false
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      - name: Terraform Init
+        run: terraform init
+      # Login to Azure CLI to support temporary runner IP allow-list
+      - name: Setup Azure CLI
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-    # Generates an execution plan for Terraform
-    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-    - name: Terraform Plan
-      id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-        
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-        
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
-        
-    # Save plan to artifacts  
-    - name: Publish Terraform Plan
-      uses: actions/upload-artifact@v4
-      with:
-        name: tfplan
-        path: tfplan
-        
-    # Create string output of Terraform Plan
-    - name: Create String Output
-      id: tf-plan-string
-      run: |
-        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-        
-        delimiter="$(openssl rand -hex 8)"
-        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-        echo "" >> $GITHUB_OUTPUT
-        echo '```terraform' >> $GITHUB_OUTPUT
-        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-        echo '```' >> $GITHUB_OUTPUT
-        echo "</details>" >> $GITHUB_OUTPUT
-        echo "${delimiter}" >> $GITHUB_OUTPUT
-        
-    # Publish Terraform Plan as task summary
-    - name: Publish Terraform Plan to Task Summary
-      env:
-        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-      run: |
-        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      #Get the IP address of the GitHub Actions runner
+      - name: Get GitHub Actions Runner IP
+        id: get-runner-ip
+        run: |
+          IP=$(curl -s https://api.ipify.org)
+          echo "Runner IP: $IP"
+          echo "TF_VAR_runner_ip=$IP/32" >> $GITHUB_ENV
+          echo "runner_ip=$IP" >> $GITHUB_OUTPUT
 
-    # If changes are detected, create a new issue
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 2
-      uses: actions/github-script@v8
-      env:
-        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-      with:
+      - name: Get storage accounts from module matching 'mta-sts'
+        id: get-storage-accounts
+        run: |
+          # Extract pairs of storage account name and resource group name separated by a comma
+          PAIRS=$(terraform state pull | jq -r '
+            .resources[]
+              | select(
+                  .type == "azurerm_storage_account"
+                  and (.module != null)
+                  and (.name | test("mta-sts"))
+                )
+              | .instances[]
+              | "\(.attributes.name),\(.attributes.resource_group_name)"
+            ' | sort -u)
+
+            echo "Found storage accounts and resource groups:"
+            echo "$PAIRS"
+
+            # Set output for later steps; replacing newlines with semicolons to keep it as one string
+            FORMATTED_OUTPUT=$(echo "$PAIRS" | paste -sd ";" -)
+            echo "storage_accounts_and_rgs=$FORMATTED_OUTPUT" >> $GITHUB_OUTPUT
+
+      - name: Temporarily Allow Runner IP and test
+        run: |
+          IFS=';' read -ra PAIRS <<< "${{ steps.get-storage-accounts.outputs.storage_accounts_and_rgs }}"  
+          for pair in "${PAIRS[@]}"; do
+            IFS=',' read -ra PARTS <<< "$pair"
+            STORAGE_ACCOUNT="${PARTS[0]}"
+             RESOURCE_GROUP="${PARTS[1]}"
+             
+            echo "➡️ Adding firewall rule for $STORAGE_ACCOUNT in $RESOURCE_GROUP..."
+            az storage account network-rule add --resource-group $RESOURCE_GROUP  --account-name $STORAGE_ACCOUNT --ip-address ${{ steps.get-runner-ip.outputs.runner_ip }} > /dev/null
+             
+            echo "⏳ Verifying access for $STORAGE_ACCOUNT..."
+            for i in {1..10}; do
+              echo "Attempt $i for $STORAGE_ACCOUNT..."
+              if az storage container list \
+                --account-name "$STORAGE_ACCOUNT" \
+                --auth-mode login >/dev/null 2>&1; then
+                echo "✅ Access confirmed for $STORAGE_ACCOUNT"
+                break
+              else
+                echo "Still waiting for firewall rule to propagate..."
+                sleep 10
+              fi
+
+              if [ "$i" -eq 10 ]; then
+                echo "❌ Firewall rule for $STORAGE_ACCOUNT not active after waiting."
+                exit 1
+              fi
+            done
+          done
+
+      # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
+
+      # Save plan to artifacts
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfplan
+          path: tfplan
+
+      # Create string output of Terraform Plan
+      - name: Create String Output
+        id: tf-plan-string
+        run: |
+          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+
+      # Publish Terraform Plan as task summary
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+
+      # If changes are detected, create a new issue
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 2
+        uses: actions/github-script@v8
+        env:
+          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const body = `${process.env.SUMMARY}`;
             const title = 'Terraform Configuration Drift Detected';
             const creator = 'github-actions[bot]'
-          
+
             // Look to see if there is an existing drift issue
             const issues = await github.rest.issues.listForRepo({
               owner: context.repo.owner,
@@ -138,17 +207,17 @@ jobs:
                 body: body
              })
             }
-            
-    # If changes aren't detected, close any open drift issues
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 0
-      uses: actions/github-script@v8
-      with:
+
+      # If changes aren't detected, close any open drift issues
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 0
+        uses: actions/github-script@v8
+        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const title = 'Terraform Configuration Drift Detected';
             const creator = 'github-actions[bot]'
-          
+
             // Look to see if there is an existing drift issue
             const issues = await github.rest.issues.listForRepo({
               owner: context.repo.owner,
@@ -167,9 +236,21 @@ jobs:
                 issue_number: issue.number,
                 state: 'closed'
               })
-            } 
-             
-    # Mark the workflow as failed if drift detected 
-    - name: Error on Failure
-      if: steps.tf-plan.outputs.exitcode == 2
-      run: exit 1
+            }
+      # Remove the storage account firewall rule for the runner IP
+      - name: Remove Runner IP from Storage Account Firewall
+        if: always()
+        run: |
+          IFS=';' read -ra PAIRS <<< "${{ steps.get-storage-accounts.outputs.storage_accounts_and_rgs }}"  
+          for pair in "${PAIRS[@]}"; do
+            IFS=',' read -ra PARTS <<< "$pair"
+            STORAGE_ACCOUNT="${PARTS[0]}"
+            RESOURCE_GROUP="${PARTS[1]}"
+            echo "Storage account: $STORAGE_ACCOUNT, Resource group: $RESOURCE_GROUP"
+            az storage account network-rule remove --resource-group $RESOURCE_GROUP  --account-name $STORAGE_ACCOUNT --ip-address ${{ steps.get-runner-ip.outputs.runner_ip }} > /dev/null
+          done
+
+      # Mark the workflow as failed if drift detected
+      - name: Error on Failure
+        if: steps.tf-plan.outputs.exitcode == 2
+        run: exit 1
