move plan and apply to separate actions

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -125,56 +125,56 @@ jobs:
                 body: body
             })
                 
-  terraform-apply:
-    name: 'Terraform Apply'
-    if: github.event_name == 'pull_request' && github.event.action == 'closed'
-    runs-on: ubuntu-latest
-    environment: production
-    #needs: [terraform-plan]
+#  terraform-apply:
+#    name: 'Terraform Apply'
+#    if: github.event_name == 'pull_request' && github.event.action == 'closed'
+#    runs-on: ubuntu-latest
+#    environment: production
+#    #needs: [terraform-plan]
 
-    env:
-      TF_VAR_runner_ip: ""
+#    env:
+#      TF_VAR_runner_ip: ""
     
-    steps:
+#    steps:
     #Get the IP address of the GitHub Actions runner
-    - name: Get GitHub Actions Runner IP
-      id: get-runner-ip
-      run: |
-          IP=$(curl -s https://api.ipify.org)
-          echo "Runner IP: $IP"
-          echo "TF_VAR_runner_ip=$IP/32" >> $GITHUB_ENV
-    
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v4
+#    - name: Get GitHub Actions Runner IP
+#      id: get-runner-ip
+#      run: |
+#          IP=$(curl -s https://api.ipify.org)
+#          echo "Runner IP: $IP"
+#          echo "TF_VAR_runner_ip=$IP/32" >> $GITHUB_ENV
+#    
+#    # Checkout the repository to the GitHub Actions runner
+#    - name: Checkout
+#      uses: actions/checkout@v4#
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+#    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+#    - name: Setup Terraform
+#      uses: hashicorp/setup-terraform@v3
+#
+#    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+#    - name: Terraform Init
+#      run: terraform init
 
     # Generates an execution plan for Terraform
     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-    - name: Terraform Plan
-      id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -var="runner-ip=${{ env.TF_VAR_runner_ip }}" -no-color -out tfplan || export exitcode=$?
+ #   - name: Terraform Plan
+ #     id: tf-plan
+ #     run: |
+ #       export exitcode=0
+ #       terraform plan -detailed-exitcode -var="runner-ip=${{ env.TF_VAR_runner_ip }}" -no-color -out tfplan || export exitcode=$?
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+#        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
+#        if [ $exitcode -eq 1 ]; then
+#          echo Terraform Plan Failed!
+#          exit 1
+#        else 
+#          exit 0
+#        fi
         
 
     # Terraform Apply
-    - name: Terraform Apply
-      if: steps.tf-plan.outputs.exitcode == '2'
-      run: terraform apply -auto-approve tfplan
+#    - name: Terraform Apply
+#      if: steps.tf-plan.outputs.exitcode == '2'
+#      run: terraform apply -auto-approve tfplan
