move plan and apply to run from same runner to allow for IP changes

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -28,20 +28,11 @@ jobs:
     env:
       #this is needed since we are running terraform with read-only permissions
       ARM_SKIP_PROVIDER_REGISTRATION: true
-      TF_VAR_runner_ip: ""
     outputs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
-    steps:
-    #Get the IP address of the GitHub Actions runner
-    - name: Get GitHub Actions Runner IP
-      id: get-runner-ip
-      run: |
-          IP=$(curl -s https://api.ipify.org)
-          echo "Runner IP: $IP"
-          echo "TF_VAR_runner_ip=$IP/32" >> $GITHUB_ENV
-    
-      # Checkout the repository to the GitHub Actions runner
+    steps:   
+    # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v4
 
@@ -127,19 +118,24 @@ jobs:
                 
   terraform-apply:
     name: 'Terraform Apply'
-    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+    if: github.event_name == 'pull_request' && github.event.action == 'closed'
     runs-on: ubuntu-latest
     environment: production
-    needs: [terraform-plan]
+    #needs: [terraform-plan]
+
+    env:
+      TF_VAR_runner_ip: ""
     
     steps:
+    #Get the IP address of the GitHub Actions runner
     - name: Get GitHub Actions Runner IP
       id: get-runner-ip
       run: |
           IP=$(curl -s https://api.ipify.org)
           echo "Runner IP: $IP"
+          echo "TF_VAR_runner_ip=$IP/32" >> $GITHUB_ENV
     
-      # Checkout the repository to the GitHub Actions runner
+    # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v4
 
@@ -151,12 +147,25 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    # Download saved plan from artifacts  
-    - name: Download Terraform Plan
-      uses: actions/download-artifact@v4
-      with:
-        name: tfplan
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -var="runner-ip=${{ env.TF_VAR_runner_ip }}" -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
 
     # Terraform Apply
     - name: Terraform Apply
+      if: steps.tf-plan.outputs.exitcode == '2'
       run: terraform apply -auto-approve tfplan
